### ISSUE TITLE
打开外部 txt 链接 CORS 错误

### ISSUE THREAD

**Issue by henryxrl** [cataerogong/SimpleTextReaderServer#1]
<img width="729" alt="image" src="https://github.com/cataerogong/SimpleTextReaderServer/assets/7662954/86225b28-9402-4b3b-9ea3-10a137c7705a">

貌似无法跨域请求哎～ 请问有办法解决这个问题吗？

**Comment by henryxrl** [comment]
是不是用你提供的 WebDAV 服务器就可以呀？能简单介绍一下如何使用吗？纯小白

**Comment by cataerogong** [comment]
呃……这个功能我都没怎么测试，当时随手另开了一个WebDAV测的。刚才看了一下，那个WebDAV设置了credentials=false，然后允许任意host访问，所以没遇到这个问题 🤣 
CORS这块我也不太懂，网上搜了一下，这个问题可能是txt文件所在的服务器上设置了不允许CORS，我试了一下，也一样错误。
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://example-files.online-convert.com/document/txt/example.txt. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.`

**Comment by cataerogong** [comment]
我用的那个简易 WebDAV 程序很简单，你去它 github 下最新的 release，配置文件 config.yaml 按照我这个配置来就行。
```yaml
# Server related settings
address: 127.0.0.1 # 本机以外访问的话，地址绑 0.0.0.0，别忘记开防火墙
port: 8000
auth: false
tls: false
cert: cert.pem
key: key.pem
prefix: /

# Default user settings (will be merged)
scope: ./strs  # webroot 根目录，可以是绝对路径
modify: false
rules:
  - path: /books/.+\.progress$
    regex: true
    allow: true
    modify: true

# CORS configuration
cors:
  enabled: true
  credentials: false
  #allowed_headers:
  #  - Depth
  #allowed_hosts:
  #  - http://localhost:8080
  #allowed_methods:
  #  - GET
  exposed_headers:
    - Content-Length
    - Content-Range
```
